spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          url: https://github.com/dhilipk/CloudMyTrip/tree/service-ci/spring-cloud-config
          searchPaths: spring-cloud-config